h/urls.py
from django.conf.urls import include, url
from h import views
from django.contrib import admin
app_name = 'h'
admin.autodiscover()

urlpatterns = [
#url(r'^article/(?P<help_id>[0-9]+)$',views.help_page,name='help_page'),
    url(r'^sign_up',views.sign_up,name='sign_up'),#注册
    url(r'^sign_in',views.sign_in,name='sign_in'),#登录
    url(r'^h_logout',views.h_logout,name='h_logout'),#退出登录
    url(r'^usermanagement',views.usermanagement,name='usermanagement'),#用户管理
    url(r'^help_h',views.help_h,name='help_h'),#帮助管理
    url(r'^deld_hp/$', views.deld_hp, name='deld_hp'),  # 删除
    url(r'^help_page/(?P<help_id>[0-9]+)$', views.help_page, name='help_page'),
    url(r'^addhelp/(?P<help_id>[0-9]+)$',views.addhelp,name='addhelp'),
    url(r'^add_action',views.add_action,name='add_action'),
    url(r'^announcement', views.announcement,name='announcement'),#公告管理
    url(r'^deld_ac/$', views.deld_ac, name='deld_ac'),#删除公告
    url(r'^a_p/(?P<a_id>[0-9]+)$',views.a_p, name='a_p'),
    url(r'^ad_ac/(?P<a_id>[0-9]+)$', views.ad_ac, name='ad_ac'),
    url(r'^add_ac', views.add_ac, name='add_ac'),
    url(r'^top_up/', views.top_up, name='top_up'),#充值管理
    url(r'^top_up_c', views.top_up_c, name='top_up_c'),
    url(r'^b_shop', views.b_shop, name='b_shop'),#代购
    url(r'^b_cancel',views.b_cancel,name='b_cancel'),
    url(r'^b_pay',views.b_pay,name='b_pay'),
    url(r'^gjyf',views.gjyf,name='gjyf'),
    url(r'^b_complete',views.b_complete,name='b_complete'),
    url(r'^b_delivery',views.b_delivery,name='b_delivery'),
    url(r'^t_shop', views.t_shop, name='t_shop'),#代运
    url(r'^yf',views.yf,name='yf'),
    url(r'^t_cancel', views.t_cancel, name='t_cancel'),
    url(r'^t_pay', views.t_pay, name='t_pay'),
    url(r'^t_complete', views.t_complete, name='t_complete'),
    url(r'^t_delivery', views.t_delivery, name='t_delivery'),
    url(r'^toushu',views.toushu,name='toushu'),#意见投诉
    url(r'^ts_p/(?P<ts_id>[0-9]+)$', views.ts_p, name='ts_p'),#查看详细
    url(r'^de_ts/$', views.de_ts, name='de_ts'),  # 删除投书
    url(r'^op',views.op,name='op'),#操作日志
    url(r'^r_password',views.r_password,name='r_password'),#系统设置
    url(r'^search/$', views.search, name='search'),#投诉搜索
    url(r'^search_u/$', views.search_u, name='search_u'),  # 搜索用户
    url(r'^search_h/$', views.search_h, name='search_h'),  # 搜索帮助
    url(r'^search_a/$', views.search_a, name='search_a'),  # 搜索公告
]

lalala/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^q/', include('q.urls', namespace="q")),
    url(r'^h/', include('h.urls', namespace="h")),
    url(r'^tinymce/',include('tinymce.urls')),
]

h/models.py
# coding:utf-8
from __future__ import unicode_literals
from tinymce.models import HTMLField
import tinymce
from django.db import models
from django.db.models.functions import datetime
#用户
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    r_money = models.FloatField()#余额
    email = models.EmailField()
    update_time = models.DateTimeField(auto_now=True)

    def toJSON(self):
        fields = []
        for field in self._meta.fields:
            fields.append(field.name)

        d = {}
        for attr in fields:
            if isinstance(getattr(self, attr), datetime.datetime):
                d[attr] = getattr(self, attr).strftime('%Y-%m-%d %H:%M:%S')
            else:
                d[attr] = getattr(self, attr)

        import json
        return json.dumps(d)

#帮助
class Help(models.Model):
    title = models.CharField(max_length=322)
    content = tinymce.models.HTMLField(verbose_name="文章详细")
    update_time = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.title

#公告
class Announcement(models.Model):
    title = models.CharField(max_length=322)
    content = models.TextField(null=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

#充值
class Top_up(models.Model):
    u = models.ForeignKey(User,on_delete=models.CASCADE)
    choice =((1,'已充值'),(2,'已驳回'),(0,'未充值'))
    state = models.IntegerField(choices=choice)#支付状态
    money = models.FloatField()#充值金额
    img = models.ImageField(upload_to='static/img')
    beizhu = models.TextField(null=True)
    payment_id = models.CharField(max_length=255)#支付方式
    create_time = models.DateTimeField(auto_now=True)

    def toJSON(self):
        fields = []
        for field in self._meta.fields:
            fields.append(field.name)

        d = {}
        for attr in fields:
            if isinstance(getattr(self, attr), datetime.datetime):
                d[attr] = getattr(self, attr).strftime('%Y-%m-%d %H:%M:%S')
            else:
                d[attr] = getattr(self, attr)

        import json
        return json.dumps(d)

#管理员
class Admin(models.Model):
    adminname = models.CharField(max_length=32)#用户名
    password = models.CharField(max_length=32)
    create_time=models.DateTimeField(auto_now=True)

    def toJSON(self):
        fields = []
        for field in self._meta.fields:
            fields.append(field.name)

        d = {}
        for attr in fields:
            if isinstance(getattr(self, attr), datetime.datetime):
                d[attr] = getattr(self, attr).strftime('%Y-%m-%d %H:%M:%S')
            else:
                d[attr] = getattr(self, attr)

        import json
        return json.dumps(d)
#地址
class Address(models.Model):
    difang = models.CharField(max_length=255)
    name=models.CharField(max_length=32)
    email=models.EmailField()
    mailnum=models.CharField(max_length=10)
    phone=models.CharField(max_length=32)
    u = models.ForeignKey(User, on_delete=models.CASCADE)

#代购表
class Buy(models.Model):
    u = models.ForeignKey(User, on_delete=models.CASCADE)#连接用户表
    ad = models.ForeignKey(Address, on_delete=models.CASCADE)
    url = models.URLField()
    gn_yunfei = models.FloatField()#国内运费金额
    gy_yunfei = models.FloatField()#国外运费金额
    zongjia = models.FloatField()#商品价格
    dj = models.FloatField()#商品单价
    num = models.IntegerField()#商品数量
    feilei = models.CharField(max_length=20)#颜色分类
    name = models.CharField(max_length=100)
    img = models.ImageField(upload_to='buyimg')
    a =((1,'未支付'),(2,'已支付'))
    b=((1,'未处理'),(2,'已处理'),(3,'未发货'),(4,'已发货'),(5,'已完成'),(6,'已取消'))
    state = models.IntegerField(choices=b)#订单状态
    payment_id = models.IntegerField(choices=a)#支付国内运费状态
    gy_py = models.IntegerField(choices=a)#支付国际运费状态
    create_time = models.DateTimeField(auto_now=True)

#代运表
class Transport(models.Model):
    u = models.ForeignKey(User, on_delete=models.CASCADE)
    ad = models.ForeignKey(Address, on_delete=models.CASCADE)
    yunfei = models.FloatField()#运费
    ddnum = models.IntegerField()#订单号
    gongsi = ((1,'申通'),(2,'圆通'),(3,'中通'),(4,'韵达'),(5,'百世')
              ,(6,'天天'),(7,'顺丰'),(8,'邮政'),(9,'EMS'),(10,'优速')
              ,(11,'安能'),(12,'快捷')
              ,(13,'德邦'),(14,'宅急送'),(15,'速尔'),(16,'苏宁'),(17,'京东')
              ,(18,'加运美'),(19,'龙邦')
              ,(20,'万象物流'),(21,'联昊通'),(22,'全峰'),(23,'国通'),(24,'信丰')
              ,(25,'菜鸟快递'),(26,'如风达')
              ,(27,'京广物流'),(28,'运通物流'),(29,'其他物流'),(30,'新邦物流'))
    leixin = ((0,'普货'),(1,'敏感货')) #货物类型
    ys = ((72,'西马（空运）ABX派送单件>=30KG请咨询客服（急件勿选）'),
            (74,'西马（空运）Skynet派送单件>=40KG请咨询客服'),               #运输类型
            (77, '东马（空运）ABX派送单件>=25KG请咨询客服'),
            (82, '西马（空运）Gdex派送'),
            (83, '新加坡（空运）dragonlink/RaidereX 派送'),
            (89, '新加坡（海运）最低消费1立方'),
            (91,'西马（海运小包）（普/敏感）偏远地区咨询客服'),
            (93, '东马sabah（海运小包)（普货/敏感）偏远地区咨询客服'),
            (96, '西马（空运）poslaju派送'),
            (98,'西马(海运）最低消费0.3CBM偏远地区收取偏远费'),
            (99, '东马海运Sarawak最低消费0.5CBM（偏远地区收取偏远费）'),
            (102,'东马（空运）Poslaju派送'),
            (106, '东马SARAWAK（海运小包)（普货/敏感）偏远地区咨询客服'),
            (107,'东马海运Sabah最低消费0.5CBM（偏远地区收取偏远费）'),
            (111, '西马（海运小包）（普/敏感）6-10KG'),
            (112,'东马sabah（海运小包)（普货/敏感）6-10'),
            (113, '东马SARAWAK（海运小包)（普货/敏感）6-10'),
            (114,'单边超过140cm或重量超68KG收取120元超长费'),
            (115, '东马海运偏远地区+250元 最低消费0.5CBM'),
            (116,'东马海运（纳闽岛LABUAN）偏远地区，最低消费1CBM'),
            (117, '西马包税(skynet/gdex)下单备注'),
            (118,'西马（空运）Airpak派送（急件勿选）'),
            (1000, '其他'))
    ddgongsi = models.IntegerField(choices=gongsi)#快递公司
    ddname=models.CharField(max_length=32)#物品名称
    ddsu=models.IntegerField()#物品数量
    dddanjia=models.FloatField()#单价
    ddbeizhu=models.CharField(max_length=255)#订单备注
    a =((1,'未支付'),(2,'已支付'))
    b=((1,'未处理'),(2,'已处理'),(3,'未发货'),(4,'已发货'),(5,'已完成'),(6,'已取消'))
    lx = models.IntegerField(choices=leixin)#货物类型
    yslx = models.IntegerField(choices=ys)#运输类型
    dsfw = models.CharField(max_length=255)#特殊服务
    beizhu = models.TextField(null=True)#服务备注
    state = models.IntegerField(choices=b)#订单状态
    payment_id = models.IntegerField(choices=a)#支付状态
    create_time = models.DateTimeField(auto_now=True)

#投诉表
class Toushu(models.Model):
    u = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    title = models.CharField(max_length=20)
    content = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    create_time = models.DateTimeField(auto_now=True)

# #搜索
# class Post(models.Model):
#     title = models.CharField(max_length=70)
#     # 正文
#     body = models.TextField()
#     # 其他属性
#
#     def __str__(self):
#         return self.title

h/forms.py
#coding:utf-8
from django import forms

#登录表单
class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"用户名","required":"required",}),
                               max_length=50,error_messages={"required":"用户名不能为空",})
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"密码","required":"required",}),
                               max_length=20,error_messages={"required":"密码不能为空",})


#注册表单
class RegForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"邮箱","required":"required",}),
                            max_length=50,error_messages={"required":"邮箱不能为空",})
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "用户名", "required": "required", }),
                               max_length=50, error_messages={"required": "用户名不能为空", })
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"密码","required":"required",}),
                               max_length=20,error_messages={"required":"密码不能为空",})
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"确认密码","required":"required",}),
                                       max_length=20,error_messages={"required":"密码不能为空",})
    def clean(self):   #自定义form的校验规则
        if not self.is_valid():  #required的字段有没有填写的is_valid()返回值就是false
            raise forms.ValidationError('所有项都必须填写')
        elif self.cleaned_data['confirm_password'] != self.cleaned_data['password']:
            raise forms.ValidationError('两次输入的密码不一致')
        else:
            cleaned_data = super(RegForm,self).clean()
        return cleaned_data   #clean()或clean_field()最后都必须返回验证完毕或者修改后的值

# #快递表单
# class ExpressForm(forms.Form):
#     postid=forms.CharField(widget=forms.TextInput(attrs={"placeholder":"快递单号","required":"required",}),
#                            max_length=40,error_messages={"required":"快递单号不能为空",})
#
# #评论表单
# class CommentForm(forms.Form):
#     comm = forms.CharField(widget=forms.Textarea(attrs={"placeholder":"商品评价","required":"required",'style': 'height: 60px;width:550px'}),
#                            max_length=100,error_messages={"required":"评价不能为空",})

h/templates/dgfp_42_hr/a_p.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>公告详情</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/>
<a href="{% url 'h:ad_ac' article.id %}">修改</a>
</body>
</html>

h/templates/dgfp_42_hr/ad_ac.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加公告</title>



</head>
<body>
<form action="{% url 'h:add_ac' %}" method="post">
    {%  csrf_token %}
    {% if article %}
        <input type="hidden" name="a_id" value="{{ article.id }}">
    <label>公告标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>公告内容
        <textarea name="content" style="width: 500px;height: 500px">{{ article.content }}</textarea>
    </label>
    <br/>
    {% else %}
        <input type="hidden" name="a_id" value="{{ article.id }}">
        <label>公告标题
        <input type="text" name="title" />
    </label>
    <br/>
    <label>公告内容
        <textarea name="content" style="width: 500px;height: 500px"></textarea>
    </label>
    <br/>
    {% endif %}
    <input type="submit" value="提交">
</form>
</body>
</html>

h/templates/dgfp_42_hr/addhelp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加帮助</title>

    <script src="/static/tiny_mce/tiny_mce.js"></script>
<script>
    tinyMCE.init({
        'mode':'textareas',
        'theme':'advanced',
        'width':450,
        'height':300
    })
</script>
</head>
<body>
<form action="{% url 'h:add_action' %}" method="post" name="addhelp">
    {%  csrf_token %}
    {% if article %}
        <input type="hidden" name="a_id" value="{{ article.id }}">
    <label>帮助标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>帮助内容
{#        <input type="text" name="content" value="{{ article.content }}"/>#}
        <textarea name="content" style="width: 500px;height: 500px">{{ article.content }}</textarea>
    </label>
    <br/>
    {% else %}
        <input type="hidden" name="a_id" value="{{ article.id }}">
        <label>帮助标题
        <input type="text" name="title" />
    </label>
    <br/>
    <label>帮助内容
{#        <input type="text" name="content" value="{{ article.content }}"/>#}
        <textarea name="content" style="width: 500px;height: 500px"></textarea>
    </label>
    <br/>
    {% endif %}
    <br/>
    <a href="#" onClick="addhelp.submit();">提交</a>
</form>
</body>
<style>
    .rich_text{
    font-size: 14px;
    color: #222222;
    line-height: 22px;
    border: 1px solid #e5e5e5;
    padding: 6px 10px;
}
.rich_text span{
    font-size: 18px;
    color: #ff3300;
}
.rich_text strong{
    font-size: 14px;
    color: #ff3300;
}
.rich_text em{
    color: #4359aa;
}
</style>
</html>

h/templates/dgfp_42_hr/announcement.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>公告管理</title>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="/static/lib/bootstrap/css/bootstrap.css">

    <link rel="stylesheet" type="text/css" href="/static/stylesheets/theme.css">
    <link rel="stylesheet" href="/static/lib/font-awesome/css/font-awesome.css">

    <script src="/static/lib/jquery-1.7.2.min.js" type="text/javascript"></script>

    <!-- Demo page code -->

    <style type="text/css">
        #line-chart {
            height:300px;
            width:800px;
            margin: 0px auto;
            margin-top: 1em;
        }
        .brand { font-family: georgia, serif; }
        .brand .first {
            color: #ccc;
            font-style: italic;
        }
        .brand .second {
            color: #fff;
            font-weight: bold;
        }
    </style>


      <style>

.black_overlay{

 display: none;

 position: absolute;

 top: 0%;

 left: 0%;

 width: 100%;

 height: 100%;

 background-color: black;

 z-index:1001;

 -moz-opacity: 0.8;

 opacity:.80;

 filter: alpha(opacity=80);

}

.white_content {

 display: none;

 position: absolute;

 top: 40%;

 left: 40%;

 width: 20%;

 height: 20%;

 border: 16px solid lightblue;

 background-color: white;

 z-index:1002;

 overflow: auto;

}

.white_content_small {

 display: none;

 position: absolute;

 top: 20%;

 left: 30%;

 width: 40%;

 height: 50%;

 border: 16px solid lightblue;

 background-color: white;

 z-index:1002;

 overflow: auto;

}

</style>

<script type="text/javascript">

//弹出隐藏层

function ShowDiv(show_div,bg_div){

 document.getElementById(show_div).style.display='block';

 document.getElementById(bg_div).style.display='block' ;

 var bgdiv = document.getElementById(bg_div);

 bgdiv.style.width = document.body.scrollWidth;

 // bgdiv.style.height = $(document).height();

 $("#"+bg_div).height($(document).height());

};

//关闭弹出层

function CloseDiv(show_div,bg_div)

{

 document.getElementById(show_div).style.display='none';

 document.getElementById(bg_div).style.display='none';

};

</script>

      <script language="javascript">
function fsubmit(obj){
obj.submit();
}
</script>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="/static/lib/font-awesome/docs/assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/lib/font-awesome/docs/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/lib/font-awesome/docs/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/lib/font-awesome/docs/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/lib/font-awesome/docs/assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <!--[if lt IE 7 ]> <body class="ie ie6"> <![endif]-->
  <!--[if IE 7 ]> <body class="ie ie7 "> <![endif]-->
  <!--[if IE 8 ]> <body class="ie ie8 "> <![endif]-->
  <!--[if IE 9 ]> <body class="ie ie9 "> <![endif]-->
  <!--[if (gt IE 9)|!(IE)]><!-->
  <body class="">
  <!--<![endif]-->

  <div class="navbar">
      <div class="navbar-inner">
        <ul class="nav pull-right">

            <li id="fat-menu" class="dropdown">
                <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-user"></i> {{ u.adminname }}
                    <i class="icon-caret-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li><a tabindex="-1" href="{% url 'h:h_logout' %}">退出</a></li>
                </ul>
            </li>

        </ul>
          <a class="brand" href="#"><span class="first">国际</span> <span class="second">物流</span></a>
      </div>
  </div>




<div class="sidebar-nav">



    <a href="{% url 'h:usermanagement' %}" class="nav-header"><i class="icon-comment"></i>用户管理</a>
    <a href="#1" class="nav-header collapsed" data-toggle="collapse"><i class="icon-exclamation-sign"></i>代购管理 <i
            class="icon-chevron-up"></i></a>
    <ul id="1" class="nav nav-list collapse">
        <li><a href="{% url 'h:b_shop' %}">待处理</a></li>
        <li><a href="{% url 'h:b_pay' %}">待支付</a></li>
        <li><a href="{% url 'h:b_delivery' %}">待发货</a></li>
        <li><a href="{% url 'h:b_cancel' %}">未完成</a></li>
        <li><a href="{% url 'h:b_complete' %}">已完成</a></li>

    </ul>

    <a href="#2" class="nav-header collapsed" data-toggle="collapse"><i class="icon-exclamation-sign"></i>代运管理 <i
            class="icon-chevron-up"></i></a>
    <ul id="2" class="nav nav-list collapse">
        <li><a href="{% url 'h:t_shop' %}">待处理</a></li>
        <li><a href="{% url 'h:t_pay' %}">待支付</a></li>
        <li><a href="{% url 'h:t_delivery' %}">待发货</a></li>
        <li><a href="{% url 'h:t_cancel' %}">未完成</a></li>
        <li><a href="{% url 'h:t_complete' %}">已完成</a></li>
    </ul>

    <a href="#3" class="nav-header collapsed" data-toggle="collapse"><i class="icon-exclamation-sign"></i>充值管理 <i
            class="icon-chevron-up"></i></a>
    <ul id="3" class="nav nav-list collapse">
        <li><a href="{% url 'h:top_up' %}">待处理充值</a></li>
        <li><a href="{% url 'h:top_up_c' %}">已处理充值</a></li>
    </ul>

    <a href="{% url 'h:announcement' %}" class="nav-header"><i class="icon-comment"></i>公告管理</a>
    <a href="{% url 'h:help_h' %}" class="nav-header"><i class="icon-comment"></i>帮助管理</a>
        <a href="{% url 'h:toushu' %}" class="nav-header"><i class="icon-comment"></i>意见投诉</a>
    <a href="{% url 'h:op' %}" class="nav-header"><i class="icon-comment"></i>操作日志</a>
    <a href="{% url 'h:r_password' %}" class="nav-header"><i class="icon-comment"></i>系统设置</a>

</div>


    <div class="content">

        <div class="header">

            <h1 class="page-title">公告管理</h1>

        <div class="container-fluid">
            <div class="row-fluid">
                            <form role="search" method="get" id="searchform" action="{% url 'h:search_a' %}">
                        {% csrf_token %}
                        <input type="search" name="q" placeholder="请输入标题" required>
                        <button type="submit" ><span class="ion-ios-search-strong">搜索</span></button>
                    </form>


<div class="btn-toolbar">
    <a href="{% url 'h:ad_ac' '0' %}"><button class="btn btn-primary"> <i class="icon-plus"></i> 新公告</button></a>
  <div class="btn-group">
  </div>
</div>
<div class="well">
    <table class="table">
      <thead>
        <tr>
          <th>标题</th>
          <th>发布时间</th>
          <th>详情</th>
          <th>操作</th>
          <th style="width: 26px;"></th>
        </tr>
      </thead>
      <tbody>
        {% for article in articles %}
        <tr>
          <td>{{ article.title }}</td>
          <td>{{ article.update_time }}</td>
          <td><a href="{% url 'h:a_p' article.id %}">查看</a> </td>
          <td>
              <form action="{% url 'h:deld_ac' %}" method="post" name="dd_a">
                  {% csrf_token %}
              <input type="hidden" name="id" value="{{ article.id }}">
{#              <input style= "background-color:transparent;border:0;" type="submit" name="" class="" value="删除">#}
                  <input id="Button1" style= "background-color:transparent;border:0;" type="button" value="删除" onclick="ShowDiv('MyDiv','fade')" />
                              <div id="fade" class="black_overlay">

</div>

 <div id="MyDiv" class="white_content">

  <div style="text-align: right; cursor: default; height: 40px;">

   <span style="font-size: 20px;" onclick="CloseDiv('MyDiv','fade')">X</span>

  </div>

 <font size="5">确定删除</font><br/>
     <input style= "background-color:transparent;border:0;float:right;color: red" type="submit" onclick="dd_a.submit()" value="删除">
{#     <a style="float:right;color: red " href="" onclick="javascript:fsubmit(document.dd_a);" >确定</a>#}




 </div>

              </form>
          </td>
        </tr>
{% endfor %}
      </tbody>
    </table>
</div>


<div class="modal small hide fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">确认删除</h3>
    </div>
    <div class="modal-body">
        <p class="error-text"><i class="icon-warning-sign modal-icon"></i>你确定要删除这条公告吗</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">取消</button>
        <button class="btn btn-danger" data-dismiss="modal">删除</button>
    </div>
</div>


            </div>
        </div>
    </div>
    </div>



    <script src="/static/lib/bootstrap/js/bootstrap.js"></script>
    <script type="text/javascript">
        $("[rel=tooltip]").tooltip();
        $(function() {
            $('.demo-cancel-click').click(function(){return false;});
        });
    </script>




  </body>
</html>